name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Atualizar submodules
        run: |
          cd ~/API-5SEM
          git fetch origin
          git reset --hard origin/main
          git submodule update --remote --merge

      - name: Parar containers
        run: |
          cd ~/API-5SEM
          docker compose down
          
      - name: Rebuildar e subir
        run: |
          cd ~/API-5SEM
          docker compose up -d --build

      - name: Verificar status
        run: |
          cd ~/API-5SEM
          docker compose ps
